import mongoose from "mongoose";
const CarSchema = new mongoose.Schema(
  {
    id: Number,
    dealerId: Number,
    userId: String,
    make: String,
    model: String,
    price: Number,
    type: String,
    kms: String,
    fuelType: String,
    fuelTankFillPrice: String,
    fuelCapacityPerTank: String,
    noOfGears: Number,
    cylinder: Number,
    features: [String],
    doors: Number,
    seats: Number,
    gearbox: String,
    engineCapacity: String,
    images: [String],
    video: String,
    sellerComments: String,
    condition: String,
    location: String,
    year: String,
    mileage: String,
    bodyType: String,
    color: String,
    batteryRange: Number,
    chargingTime: Number,
    engineSize: Number,
    enginePower: Number,
    fuelConsumption: Number,
    isFinance: String,
    slug: String,
    co2Emission: Number,
    driveType: String,
    imageUrls: [],
    status: { type: Number, default: 0 },
  },
  { timestamps: true },
);

export default mongoose.models.Car || mongoose.model("Car", CarSchema);
